Controllers/REST/SalariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AlimBio.Data;
using AlimBio.Models;
using Microsoft.AspNetCore.Authorization;

namespace AlimBio.Controllers.REST
{

    [Route("api/[controller]")]
    [ApiController]
    public class SalariesController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public SalariesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/Salaries
        [Authorize]
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Salarie>>> GetSalaries()
        {
            if (_context.Salaries == null)
            {
                return NotFound();
            }
            return await _context.Salaries.ToListAsync();
        }

        // GET: api/Salaries/5
        [Authorize]
        [HttpGet("{id}")]
        public async Task<ActionResult<Salarie>> GetSalarie(int id)
        {
            if (_context.Salaries == null)
            {
                return NotFound();
            }
            var salarie = await _context.Salaries.FindAsync(id);

            if (salarie == null)
            {
                return NotFound();
            }

            return salarie;
        }

        // PUT: api/Salaries/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [Authorize]
        [HttpPut("{id}")]
        public async Task<IActionResult> PutSalarie(int id, Salarie salarie)
        {
            if (id != salarie.Id)
            {
                return BadRequest();
            }

            _context.Entry(salarie).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SalarieExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Salaries
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [Authorize]
        [HttpPost]
        public async Task<ActionResult<Salarie>> PostSalarie(Salarie salarie)
        {
            if (_context.Salaries == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Salaries'  is null.");
            }
            _context.Salaries.Add(salarie);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetSalarie", new { id = salarie.Id }, salarie);
        }

        // DELETE: api/Salaries/5
        [Authorize]
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteSalarie(int id)
        {
            if (_context.Salaries == null)
            {
                return NotFound();
            }
            var salarie = await _context.Salaries.FindAsync(id);
            if (salarie == null)
            {
                return NotFound();
            }

            _context.Salaries.Remove(salarie);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool SalarieExists(int id)
        {
            return (_context.Salaries?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/WEB/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using AlimBio.Data;
using AlimBio.Models;
using AlimBio.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace AlimBio.Controllers.WEB
{
    public class MessagesController : Controller
    {
        private readonly IMessageService _messageService;

        public MessagesController(IMessageService messageService)
        {
            _messageService = messageService;
        }

        // GET: Messages
        public async Task<IActionResult> Index()
        {
            var messages = await _messageService.GetAllMessagesAsync();
            return View(messages);
        }

        // GET: Messages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _messageService.GetMessageByIdAsync(id.Value);

            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // GET: Messages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Messages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see <http://go.microsoft.com/fwlink/?LinkId=317598>.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Sujet,Details")] Message message)
        {
            if (ModelState.IsValid)
            {
                await _messageService.CreateMessageAsync(message);
                return RedirectToAction(nameof(Index));
            }
            return View(message);
        }

        [Authorize]
        // GET: Messages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _messageService.GetMessageByIdAsync(id.Value);

            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        [Authorize]
        // POST: Messages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see <http://go.microsoft.com/fwlink/?LinkId=317598>.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Sujet,Details")] Message message)
        {
            if (id != message.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _messageService.UpdateMessageAsync(message);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await MessageExists(message.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(message);
        }

        private async Task<bool> MessageExists(int id)
        {
            var message = await _messageService.GetMessageByIdAsync(id);
            return message != null;
        }

        [Authorize]
        // GET: Messages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _messageService.GetMessageByIdAsync(id.Value);

            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        [Authorize]
        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var message = await _messageService.GetMessageByIdAsync(id);

            if (message == null)
            {
                return NotFound();
            }

            await _messageService.DeleteMessageAsync(message.Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/WEB/SitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using AlimBio.Data;
using AlimBio.Models;
using AlimBio.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace AlimBio.Controllers.WEB
{
    public class SitesController : Controller
    {
        private readonly ISiteService _SiteService;
        private readonly IEntrepriseService _EntrepriseService;
        private readonly IVilleService _VilleService;

        public SitesController(ISiteService SiteService, IEntrepriseService EntrepriseService, IVilleService VilleService)
        {
            _SiteService = SiteService;
            _EntrepriseService = EntrepriseService;
            _VilleService = VilleService;
        }

        // GET: Sites
        public async Task<IActionResult> Index()
        {
            var Sites = await _SiteService.GetAllSitesAsync();
            return View(Sites);
        }

        // GET: Sites/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Site = await _SiteService.GetSiteByIdAsync(id.Value);

            if (Site == null)
            {
                return NotFound();
            }

            return View(Site);
        }

        // GET: Sites/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["EntrepriseId"] = new SelectList(_EntrepriseService.GetAllEntreprisesAsync().Result, "Id", "NomEntreprise");
            ViewData["VilleId"] = new SelectList(_VilleService.GetAllVillesAsync().Result, "Id", "NomVille");
            return View();
        }

        // POST: Sites/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see <http://go.microsoft.com/fwlink/?LinkId=317598>.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomSite,CodePostal")] Site Site)
        {
            if (ModelState.IsValid)
            {
                await _SiteService.CreateSiteAsync(Site);
                return RedirectToAction(nameof(Index));
            }
            return View(Site);
        }
        [Authorize]
        // GET: Sites/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Site = await _SiteService.GetSiteByIdAsync(id.Value);

            if (Site == null)
            {
                return NotFound();
            }

            return View(Site);
        }

        // POST: Sites/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see <http://go.microsoft.com/fwlink/?LinkId=317598>.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomSite,CodePostal")] Site Site)
        {
            if (id != Site.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _SiteService.UpdateSiteAsync(Site);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await SiteExists(Site.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(Site);
        }

        private Task<bool> SiteExists(int id)
        {
            throw new NotImplementedException();
        }

        // GET: Sites/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Site = await _SiteService.GetSiteByIdAsync(id.Value);

            if (Site == null)
            {
                return NotFound();
            }

            return View(Site);
        }

        // POST: Sites/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Site = await _SiteService.GetSiteByIdAsync(id);

            if (Site == null)
            {
                return NotFound();
            }

            await _SiteService.DeleteSiteAsync(Site.Id);
            return RedirectToAction(nameof(Index));
        }


    }
}

Controllers/WEB/VillesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using AlimBio.Data;
using AlimBio.Models;
using AlimBio.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace AlimBio.Controllers.WEB
{
    public class VillesController : Controller
    {
        private readonly IVilleService _villeService;

        public VillesController(IVilleService villeService)
        {
            _villeService = villeService;
        }

        // GET: Villes
        public async Task<IActionResult> Index()
        {
            var villes = await _villeService.GetAllVillesAsync();
            return View(villes);
        }

        // GET: Villes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ville = await _villeService.GetVilleByIdAsync(id.Value);

            if (ville == null)
            {
                return NotFound();
            }

            return View(ville);
        }

        // GET: Villes/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Villes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see <http://go.microsoft.com/fwlink/?LinkId=317598>.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomVille,CodePostal")] Ville ville)
        {
            if (ModelState.IsValid)
            {
                await _villeService.CreateVilleAsync(ville);
                return RedirectToAction(nameof(Index));
            }
            return View(ville);
        }

        // GET: Villes/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ville = await _villeService.GetVilleByIdAsync(id.Value);

            if (ville == null)
            {
                return NotFound();
            }

            return View(ville);
        }

        // POST: Villes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see <http://go.microsoft.com/fwlink/?LinkId=317598>.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomVille,CodePostal")] Ville ville)
        {
            if (id != ville.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _villeService.UpdateVilleAsync(ville);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await VilleExists(ville.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ville);
        }

        private Task<bool> VilleExists(int id)
        {
            throw new NotImplementedException();
        }

        // GET: Villes/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ville = await _villeService.GetVilleByIdAsync(id.Value);

            if (ville == null)
            {
                return NotFound();
            }

            return View(ville);
        }

        // POST: Villes/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ville = await _villeService.GetVilleByIdAsync(id);

            if (ville == null)
            {
                return NotFound();
            }

            await _villeService.DeleteVilleAsync(ville.Id);
            return RedirectToAction(nameof(Index));
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"] - AlimBio</title>
    <meta content='@ViewData["Description"]' name="description">
    <meta content='@ViewData["keywords"]' name="keywords">

    <!-- Favicons -->
    <link href="./favicon.png" rel="icon">
    <link href="./favicon.png" rel="apple-touch-icon">
<!-- styles -->
<!-- base | always include -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          rel="stylesheet" />
   <script src='https://api.mapbox.com/mapbox-gl-js/v2.4.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.4.1/mapbox-gl.css' rel='stylesheet' />


    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet" asp-append-version="true">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" asp-append-version="true">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet" asp-append-version="true">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet" asp-append-version="true">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet" asp-append-version="true">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet" asp-append-version="true">
    <link href="~/assets/css/style.css" rel="stylesheet" asp-append-version="true">


</head>
<body>



    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">

            <h1 class="logo me-auto"><a href="/"><span>Alimo</span>Bio</a></h1>

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    <li><a asp-controller="Home" asp-action="Index" class="active">Accueil</a></li>


                    <li><a asp-area="" asp-controller="Salaries" asp-action="Index">Equipe</a></li>
                    <li><a asp-area="" asp-controller="Services" asp-action="Index">Services</a></li>
                    <li><a asp-area="" asp-controller="Villes" asp-action="Index">Villes</a></li>
                    <li><a asp-area="" asp-controller="Sites" asp-action="Index">Sites</a></li>
                    <li><a asp-area="" asp-controller="Entreprises" asp-action="Index">Entreprises</a></li>
                    <li><a asp-area="" asp-controller="Messages" asp-action="Create">Contact</a></li>
                    <li><a class="bg-dark p-2 rounded-circle" href="/swagger">API</a></li>
                    <partial name="_LoginPartial" />

                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->


        </div>
    </header><!-- End Header -->


    <div class="container-fluid">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <!-- ======= Footer ======= -->
    <footer id="footer">

        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6 footer-contact">
                        <h3>AlimoBio</h3>
                        <p>
                            13 Rue André Callac  <br>
                            Saint-Etienne-du-Rouvray 76000<br>
                            France <br><br>
                            <strong>Tel:</strong> +1 5589 55488 55<br>
                            <strong>E-mail:</strong> info@example.com<br>
                        </p>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>liens outiles</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="/">Accueil</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a asp-controller="Services" asp-action="Index">Services</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a asp-controller="Salaries" asp-action="Index">Salariés</a></li>
                            <li> <i class="bx bx-chevron-right"></i> <a asp-controller="Home" asp-action="Privacy">Politique de confidentialité</a></li>
                            <li> <i class="bx bx-chevron-right"></i> <a asp-controller="Home" asp-action="CGV">CGV</a></li>

                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a asp-controller="Services" asp-action="Index">Marketing</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a asp-controller="Services" asp-action="Index">Informatique</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a asp-controller="Services" asp-action="Index">Adminisrateur</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-newsletter">
                        <h4>Nous sommes à l'écoute</h4>
                        <p>Pour toute autre demande vous pouvez nous contacter via la formulaire</p>
                         <a asp-controller="Messages" asp-action="Create" class="btn btn-primary">Prendre contact</a>
                    </div>

                </div>
            </div>
        </div>

        <div class="container d-md-flex py-4">

            <div class="me-md-auto text-center text-md-start">
                <div class="copyright">
                    Copyright &copy; <strong><span>Alimobio</span></strong>. tous les droits sont réservés pour <a href="#">AlimBio</a>
                </div>

            </div>

        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->


    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/waypoints/noframework.waypoints.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <!-- Vendor CSS Files -->
    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)



</body>
</html>